# Generated by Django 5.1 on 2024-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ifsc',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
