# Generated by Django 5.1 on 2024-09-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bank_name_alter_branch_ifsc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'managed': False},
        ),
    ]
