# Generated by Django 5.1 on 2024-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_bank_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_ifsc',
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ifsc',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='bank',
            table='banks',
        ),
    ]
