# Generated by Django 5.1 on 2024-09-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_remove_branch_unique_ifsc_alter_branch_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': False},
        ),
    ]
